<<<<<<< HEAD
site_name: AutomaTEC

repo_name: 'Pipeline Finatec'
=======
site_name: Pipeline Finatec

repo_name: 'Pipeline Finatecs'
>>>>>>> parent of fba4d38 (refact: limpando ambiente de desenvolvimento)
repo_url: https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/
site_url: https://raqueleucaria.github.io/05_PipelineFinatec/
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt-BR

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide: 
    - 

  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk

  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Modo Claro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Modo Escuro

nav:
  - Home: index.md
<<<<<<< HEAD
  - Planejamento:
    - Contexto: planejamento/contexto.md
    - Fluxograma: planejamento/fluxograma.md
    - Requisitos:
      - Elicitação: planejamento/requisitos/elicitacao.md
      - Priorização: planejamento/requisitos/priorizacao.md
    - Backlog: planejamento/backlog/backlog.md
    # - Escopo: planejamento/escopo.md
    #- Tecnologias: planejamento/tecnologias.md
    - RoadMap: planejamento/roadmap.md
    # - Story Mapping: planejamento/StoryMapping.md
=======
  - Atas: 
    - 06/29 - Reunião Grupo: atas/06-29.md
    - 11/07 - Reunião Grupo: atas/07-11.md
    - 20/07 - Reunião 2 FINATEC: atas/07-20.md
    - 27/07 - Reunião TI (cancelada): atas/07-27.md
    - 01/08 - Reunião TI : atas/08-01.md
    - 10/08 - Reunião Grupo : atas/08-10.md
  - Planejamento:
    - Escopo: planejamento/escopo.md
    - Metodologia: planejamento/metodologia.md
    - Tecnologias: planejamento/tecnologias.md
    - Heatmap: planejamento/heatmap.md
>>>>>>> parent of fba4d38 (refact: limpando ambiente de desenvolvimento)
  - Treinamento: 
    - Treinamentos: 
      - Mkdocs: treinamento/treinamentos/mkdocs.md
    - Estudos Individuais:
      - Linguagens e frameworks: treinamento/estudos_individuais/linguagem_framework.md
      - Metodologias: treinamento/estudos_individuais/metodologias.md
      - Pipeline de Dados: treinamento/estudos_individuais/PipelinedeDados.md
      - Fundamentos de Banco de Dados: treinamento/estudos_individuais/fundamentosBD.md
<<<<<<< HEAD
  - Atas: 
    - 06/29 - Reunião Grupo: atas/06-29.md
    - 11/07 - Reunião Grupo: atas/07-11.md
    - 20/07 - Reunião 2 FINATEC: atas/07-20.md
    - 27/07 - Reunião TI (cancelada): atas/07-27.md
    - 01/08 - Reunião TI : atas/08-01.md
=======
    

>>>>>>> parent of fba4d38 (refact: limpando ambiente de desenvolvimento)
