site_name: TIC Brisa - Grupo 5

repo_name: 'Pipeline Finatecs'
repo_url: https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/
site_url: https://raqueleucaria.github.io/05_PipelineFinatec/
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt-BR

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide: 
    - 

  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk

  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Modo Claro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Modo Escuro

nav:
  - Home: index.md
  - Atas: 
    - 11/07 - Reuni達o Grupo: atas/07-11.md
    - 20/07 - Reuni達o 2 FINATEC: atas/07-20.md
    - 27/07 - Reuni達o TI (cancelada): atas/07-27.md
    - 01/08 - Reuni達o TI : atas/08-01.md
  - Planejamento:
    - Escopo: planejamento/escopo.md
    - Metodologia: planejamento/metodologia.md
    - Tecnologias: planejamento/tecnologias.md
    - Heatmap: planejamento/heatmap.md
  - Treinamento: treinamento/issues.md
